// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcAG-P7xWq1p2SCgil0IJIm3euisHeAI',
    appId: '1:44563271076:web:51e64864bdeb0ad9c74531',
    messagingSenderId: '44563271076',
    projectId: 'vapor-engine',
    authDomain: 'vapor-engine.firebaseapp.com',
    databaseURL:
        'https://vapor-engine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vapor-engine.firebasestorage.app',
    measurementId: 'G-Z7WL0TWVS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50ussmvofyUaC1RMxfEnctqFw24NT-pA',
    appId: '1:44563271076:android:f90104f5e9828de3c74531',
    messagingSenderId: '44563271076',
    projectId: 'vapor-engine',
    databaseURL:
        'https://vapor-engine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vapor-engine.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5POvLq8aQbytcJQngcam1bwzKbSoCtU',
    appId: '1:44563271076:ios:cb0ccf127f211b9ac74531',
    messagingSenderId: '44563271076',
    projectId: 'vapor-engine',
    databaseURL:
        'https://vapor-engine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vapor-engine.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj5POvLq8aQbytcJQngcam1bwzKbSoCtU',
    appId: '1:44563271076:ios:cb0ccf127f211b9ac74531',
    messagingSenderId: '44563271076',
    projectId: 'vapor-engine',
    databaseURL:
        'https://vapor-engine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vapor-engine.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcAG-P7xWq1p2SCgil0IJIm3euisHeAI',
    appId: '1:44563271076:web:73e336dbc5ac3340c74531',
    messagingSenderId: '44563271076',
    projectId: 'vapor-engine',
    authDomain: 'vapor-engine.firebaseapp.com',
    databaseURL:
        'https://vapor-engine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vapor-engine.firebasestorage.app',
    measurementId: 'G-830XKWG01K',
  );
}
