name: Build & Deploy Web

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release

      - name: Zip Web Build
        working-directory: build/web
        run: zip -r ../../vapor-web.zip .

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vapor-web
          path: vapor-web.zip
          retention-days: 7

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VAPOR_ENGINE }}'
          projectId: vapor-engine
          channelId: live
