name: Build Windows

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build Windows
        run: |
          flutter pub get
          flutter build windows --release

      - name: Zip Windows Build
        working-directory: build/windows/x64/runner/Release
        run: Compress-Archive -Path * -DestinationPath ../../../../../vapor-windows.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vapor-windows
          path: vapor-windows.zip
          retention-days: 7
